CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    ipfs_hash TEXT NOT NULL,
    username VARCHAR(255) NOT NULL UNIQUE,
    metamask_id VARCHAR(42) NOT NULL UNIQUE,
    phone_number VARCHAR(20) NOT NULL,
    license_number VARCHAR(20) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
